# Generated by Django 5.1.8 on 2025-04-06 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
    ]
