# Generated by Django 5.1.8 on 2025-04-06 23:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-pub_date'], 'verbose_name_plural': 'News'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='href',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='news',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(default='', max_length=100),
        ),
    ]
