# Generated by Django 5.1.8 on 2025-04-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alias',
            field=models.CharField(default='Hogares', max_length=64),
            preserve_default=False,
        ),
    ]
