# Generated by Django 5.2.3 on 2025-06-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_alter_profile_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefineryRevenueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('website', models.CharField(max_length=255, verbose_name='Sitio Web')),
                ('clicks', models.IntegerField(default=0, verbose_name='Clicks')),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ingresos')),
                ('impressions', models.IntegerField(default=0, verbose_name='Impresiones')),
                ('tag_loads', models.IntegerField(default=0, verbose_name='Cargas de Tags')),
                ('page_with_ads', models.IntegerField(default=0, verbose_name='Páginas con Anuncios')),
                ('cpm', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='CPM')),
                ('view_measured_impressions', models.IntegerField(default=0, verbose_name='Impresiones Medidas')),
                ('viewable_impressions', models.IntegerField(default=0, verbose_name='Impresiones Visibles')),
                ('viewable_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa de Visibilidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Reporte de Ingresos Refinery',
                'verbose_name_plural': 'Reportes de Ingresos Refinery',
                'ordering': ['-date', 'website'],
                'indexes': [models.Index(fields=['date'], name='bets_refine_date_1e3783_idx'), models.Index(fields=['website'], name='bets_refine_website_f21d50_idx'), models.Index(fields=['date', 'website'], name='bets_refine_date_0fd64e_idx')],
                'unique_together': {('date', 'website')},
            },
        ),
    ]
