# Generated by Django 5.2.3 on 2025-06-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_refineryrevenuereport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refineryrevenuereport',
            old_name='viewable_rate',
            new_name='viewability_rate',
        ),
    ]
