# Generated by Django 5.2.3 on 2025-06-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0004_rename_viewable_rate_refineryrevenuereport_viewability_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='refineryrevenuereport',
            name='impressions_net',
            field=models.IntegerField(default=0, verbose_name='Impresiones Netas'),
        ),
    ]
