# Generated by Django 5.2.3 on 2025-06-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0005_refineryrevenuereport_impressions_net'),
    ]

    operations = [
        migrations.AddField(
            model_name='refineryrevenuereport',
            name='revenue_net',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ingresos Netos'),
        ),
    ]
