# Generated by Django 5.2.3 on 2025-06-28 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0006_refineryrevenuereport_revenue_net'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='alias',
        ),
    ]
